# Generated by Django 5.0.6 on 2024-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_type',
            name='static_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
