# Generated by Django 5.0.6 on 2024-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_response_type_static_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='survey_key',
            constraint=models.UniqueConstraint(fields=('survey', 'key'), name='uniq_survey_key'),
        ),
    ]
