# Generated by Django 5.0.6 on 2024-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_key_uniq_survey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
