# Generated by Django 5.0.6 on 2024-07-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_question_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('translated_name', models.CharField()),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='question_translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.language'),
        ),
    ]
